[project]
name = "microdados-estabelcimentos"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Evaldo", email = "evaldoazeredoc@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "basedosdados>=2.0.3",
    "jupyter>=1.1.1",
    "matplotlib>=3.11.2",
    "pandas>=3.0.5",
    "pyspark>=4.2.0",
    "python-dotenv>=1.2.3",
    "seaborn>=0.13.2",
    "yfinance>=1.7.0",
]

[project.scripts]
microdados-estabelcimentos = "microdados_estabelcimentos:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
